#!/bin/bash

echo "l \"$1.hex\"" > $1.run
echo "b 0" >> $1.run
echo "." >> $1.run
echo ". 1000" >> $1.run
echo "x10" >> $1.run

../../rv64sim < $1.run | diff --strip-trailing-cr - expected/$1.log

rm -f $1.run
